# Generated by Django 4.0.5 on 2022-06-27 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BMRdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=6)),
                ('Weight', models.IntegerField()),
                ('Height', models.FloatField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Life_style', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly active', 'Lightly active'), ('Moderately active', 'Moderately active'), ('Very active', 'Very active'), ('Extra active', 'Extra active')], default='S', max_length=17)),
                ('bmr_result', models.IntegerField(null=True)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='addFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meals', models.CharField(choices=[('BreakFast', 'Breakfast'), ('Lhnch', 'Lunch'), ('Dinner', 'Dinner')], default='BreakFast', max_length=9)),
                ('Food_Name', models.CharField(max_length=12)),
                ('Quantity', models.IntegerField()),
                ('Calories', models.IntegerField()),
                ('Date', models.DateField(null=True)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
