# Generated by Django 3.2 on 2022-10-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calories_Calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmrdata',
            name='Life_style',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly active', 'Lightly active'), ('Moderately active', 'Moderately active'), ('Very active', 'Very active'), ('Extra active', 'Extra active')], default='Sedentary', max_length=17),
        ),
    ]
